extends:
  - secrets.yaml

external:
  redis:
    host: 127.0.0.1
    port: 6379
    db: 0

logging:
  version: 1
  formatters:
    simple:
      format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      level: INFO
      formatter: simple
      stream: ext://sys.stdout
  loggers:
    ocelot:
      level: INFO
      handlers: [console]
      propagate: no
  root:
    level: WARNING
    handlers: [console]
