datastore:
  pipelines:
    96feda22-f80d-4cee-ad51-4e18de0b655a:
      name: 'XKCD Check'

  tasks:
    cb332d4f-3f51-4a89-b68b-edf1a0b882f0:
      type: URLInput
      config:
        url: http://xkcd.com/rss.xml
    4cde9299-706c-4375-a82d-640980bc6bf4:
      type: XMLParseOperation
      config: {}
    293e636f-75ec-4326-bfea-475822e429b6:
      type: XMLRSSParseOperation
      config: {}
    c3b2b54c-4cda-43ee-b4f6-b63436806d64:
      type: NewItemFilterOperation
      config:
        identifier: 'xkcd-items'
    af39bfda-8187-4b73-9759-7e325811b952:
      type: DictMapperOperation
      config:
        config:
          title:
            type: extract
            config:
              path: '$.title'
          description:
            type: extract
            config:
              path: '$.description'
    c9e82e66-3d07-42ec-bcdc-d20050f7b592:
      type: DictPatternExtractOperation
      config:
        config:
          paths:
            - '$.description'
          pattern: 'src="(.*?)"'
    18887ac8-a2a8-47b0-a9d6-91528b8cf87d:
      type: MessageFormatOperation
      config:
        message: |
          XKCD Lineup:
          ----
          {% for item in data %}
          {{item.title}}
          {{item.description}}
          {% endfor %}
    15b3a330-2bcc-4cbb-bb53-d894244f0f27:
      type: DictCreateOperation
      config:
        config:
          key: plain_message
    cad413a2-869c-4c82-84e4-df459a31acf9:
      type: DictMapperOperation
      config:
        config:
          plain_message:
            type: extract
            config:
              path: '$.plain_message'
          from_email:
            type: insert
            config:
              value: 'ocelot@caleb.io'
          subject:
            type: insert
            config:
              value: 'New XKCD Items'
          to_email:
            type: insert
            config:
              value: 'me@caleb.io'
    b40786e1-dbb2-43ab-a074-a0fd74211d97:
      type: LogOutput
      config:
        log_name: xkcd
    e74fbf87-f15a-4286-a8ee-e80ddbe756a5:
      type: EmailOutput
      config: {}

  task_connections:
    c76107e3-0d11-4867-a56a-18cdd0d379c8: # URL -> XML
      from_task_id: cb332d4f-3f51-4a89-b68b-edf1a0b882f0
      to_task_id: 4cde9299-706c-4375-a82d-640980bc6bf4
      pipeline_id: 96feda22-f80d-4cee-ad51-4e18de0b655a
    998ce7e0-d09b-4440-bfec-864e0e7f95f3: # XML -> RSS
      from_task_id: 4cde9299-706c-4375-a82d-640980bc6bf4
      to_task_id: 293e636f-75ec-4326-bfea-475822e429b6
      pipeline_id: 96feda22-f80d-4cee-ad51-4e18de0b655a
    50818c41-9d5e-4300-8c80-73dc40973c17: # RSS -> New Item
      from_task_id: 293e636f-75ec-4326-bfea-475822e429b6
      to_task_id: c3b2b54c-4cda-43ee-b4f6-b63436806d64
      pipeline_id: 96feda22-f80d-4cee-ad51-4e18de0b655a
    aaff7cc3-136e-449e-9fed-54fa000c1e72:  # New Item -> Extractor
      from_task_id: c3b2b54c-4cda-43ee-b4f6-b63436806d64
      to_task_id: af39bfda-8187-4b73-9759-7e325811b952
      pipeline_id: 96feda22-f80d-4cee-ad51-4e18de0b655a
    a2fcaf7f-c633-4bb9-a674-64e018221f22: # Extractor -> Updater
      from_task_id: af39bfda-8187-4b73-9759-7e325811b952
      to_task_id: c9e82e66-3d07-42ec-bcdc-d20050f7b592
      pipeline_id: 96feda22-f80d-4cee-ad51-4e18de0b655a
    71bf5cbe-975a-45f0-a90b-f586dc01232c: # Updater -> Message
      from_task_id: c9e82e66-3d07-42ec-bcdc-d20050f7b592
      to_task_id: 18887ac8-a2a8-47b0-a9d6-91528b8cf87d
      pipeline_id: 96feda22-f80d-4cee-ad51-4e18de0b655a
    f09edb7a-d255-4e0d-9b28-62809d63c665: # Message -> DictCreate
      from_task_id: 18887ac8-a2a8-47b0-a9d6-91528b8cf87d
      to_task_id: 15b3a330-2bcc-4cbb-bb53-d894244f0f27
      pipeline_id: 96feda22-f80d-4cee-ad51-4e18de0b655a
    799da080-bf80-4573-a729-997ba0900cbc: # DictCreate -> Map
      from_task_id: 15b3a330-2bcc-4cbb-bb53-d894244f0f27
      to_task_id: cad413a2-869c-4c82-84e4-df459a31acf9
      pipeline_id: 96feda22-f80d-4cee-ad51-4e18de0b655a
    49ca8ca8-5355-4ee1-bb4d-ad23ae3d1f68: # Map -> Log
      from_task_id: cad413a2-869c-4c82-84e4-df459a31acf9
      to_task_id: b40786e1-dbb2-43ab-a074-a0fd74211d97
      pipeline_id: 96feda22-f80d-4cee-ad51-4e18de0b655a
    1f65df09-5cb8-414d-87bd-606f256c3cec:
      from_task_id: cad413a2-869c-4c82-84e4-df459a31acf9
      to_task_id: e74fbf87-f15a-4286-a8ee-e80ddbe756a5
      pipeline_id: 96feda22-f80d-4cee-ad51-4e18de0b655a
